[image_paths]
total_temp_small_path = ./tempImagesSmall
total_temp_large_path = ./tempImagesSLarge
total_zoom_small_path = ./images_small
total_zoom_large_path = ./images_large
obj_detect_img_path = ./obj_detect_images
; type_image_path =  /home/tali/FieldDetection/Type_Classify/images

; sport_temp_path =  /home/tali/FieldDetection/Sport_Type/tempImages
; sport_zoom_path =   /home/tali/FieldDetection/Sport_Type/zoomedImages


[model_paths]
type_model = ./Type_Model
sport_model = ./Detection_Modal_With_Buildings
infield_model = ./infieldDetection/runs/detect/train/weights/best.pt
obd_model = ./weights/best.pt

; [type_paths]
; test = /home/tali/FieldDetection/Type_Classify/splitImages/test
; train = /home/tali/FieldDetection/Type_Classify/splitImages/train
; val = /home/tali/FieldDetection/Type_Classify/splitImages/val

; [sport_paths]
; test =  /data/Classifier_Data/Sport_Type_Images/test
; train =  /data/Classifier_Data/Sport_Type_Images/train
; val =  /data/Classifier_Data/Sport_Type_Images/val


[error]
getImage_total_error = total_error.xlsx
; getImage_type_error = type_error.xlsx
; getImage_sport_error = sport_error.xlsx

[find_shift]
infield_threshold = 85



[database]
hostname = localhost
database = gameplaydb
username = postgres
password = AdrianGameplay
port_id = 5432
batch_size = 1000

  
